name: Software documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create documentation directory
      run: |
        mkdir -p docs/Software/respi-firmware
    - name: Generate documentation for respi-firmware
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'src/code/Doxyfile'
    - name: Archive documentation
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/Software/
